name: vtt

services:
  vtt-13:
    image: jignate/vtt:13
    ports:
      - "30013:30000"
    volumes:
      - C:/path/to/vtt/13:/data

  vtt-12:
    image: jignate/vtt:12
    ports:
      - "30012:30000"
    volumes:
      - C:/path/to/vtt/12:/data

  vtt-11:
    image: jignate/vtt:11
    ports:
      - "30011:30000"
    volumes:
      - C:/path/to/vtt/11:/data
